# Generated by Django 6.0.4 on 2026-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_value', models.IntegerField(verbose_name='N արժեք')),
                ('k_value', models.IntegerField(verbose_name='K արժեք')),
                ('time_fast_ms', models.FloatField(verbose_name='Արագ մեթոդի ժամանակ (մվ)')),
                ('time_slow_ms', models.FloatField(blank=True, null=True, verbose_name='Դանդաղ մեթոդի ժամանակ (մվ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման ամսաթիվ')),
            ],
        ),
    ]
