# Generated by Django 6.0.4 on 2026-04-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Անվանում (օրինակ՝ Զուգորդություններ)')),
                ('slug', models.CharField(max_length=50, verbose_name='Բանալի-բառ (օրինակ՝ combinations)')),
                ('fast_method_name', models.CharField(max_length=150, verbose_name='Օպտիմալի անվանում (օրինակ՝ Բանաձև O(1))')),
                ('slow_method_name', models.CharField(max_length=150, verbose_name='Ոչ օպտիմալի անվանում (օրինակ՝ Ռեկուրսիա)')),
            ],
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='algorithm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='algorithms.algorithm', verbose_name='Ալգորիթմ'),
        ),
    ]
