# Generated by Django 6.0.4 on 2026-04-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_algorithm_calculationhistory_algorithm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationhistory',
            name='k_value',
        ),
        migrations.RemoveField(
            model_name='calculationhistory',
            name='n_value',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='required_inputs',
            field=models.CharField(default='n,k', max_length=100),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='input_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='fast_method_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='slow_method_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='slug',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='algorithm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='algorithms.algorithm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='time_fast_ms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calculationhistory',
            name='time_slow_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
