# Generated by Django 6.0.4 on 2026-04-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_remove_calculationhistory_k_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='fast_explanation',
            field=models.TextField(blank=True, default='', verbose_name='Արագի բացատրություն'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='fast_formula',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Արագի բանաձև'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='slow_explanation',
            field=models.TextField(blank=True, default='', verbose_name='Դանդաղի բացատրություն'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='slow_formula',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Դանդաղի բանաձև'),
        ),
    ]
