# Generated by Django 6.0.2 on 2026-05-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "algorithms",
            "0004_algorithm_fast_explanation_algorithm_fast_formula_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Խնդրի Վերնագիր"),
                ),
                (
                    "slug",
                    models.SlugField(help_text="Օրինակ՝ combinations", unique=True),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "🟢 Հեշտ"),
                            ("Medium", "🟡 Միջին"),
                            ("Hard", "🔴 Բարդ"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Խնդրի Պահանջը (HTML ֆորմատով)"),
                ),
                ("constraints", models.TextField(verbose_name="Սահմանափակումներ")),
                (
                    "starter_code",
                    models.TextField(verbose_name="Սկզբնական կոդ (Boilerplate)"),
                ),
                (
                    "test_cases",
                    models.JSONField(
                        help_text='Օրինակ: [{"inputs": "4, 2", "expected": "[[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]]"}]',
                        verbose_name="Թեստեր (JSON)",
                    ),
                ),
            ],
        ),
    ]
