# Generated by Django 6.0.2 on 2026-05-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0005_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="topic",
            field=models.CharField(
                choices=[
                    ("Կոմբինատորիկա", "Կոմբինատորիկա"),
                    ("Դինամիկ Ծրագրավորում", "Դինամիկ Ծրագրավորում"),
                    ("Գրաֆների Տեսություն", "Գրաֆների Տեսություն"),
                    ("Տեսակավորում և Որոնում", "Տեսակավորում և Որոնում"),
                    ("Մաթեմատիկա", "Մաթեմատիկա"),
                ],
                default="Կոմբինատորիկա",
                max_length=100,
                verbose_name="Ալգորիթմի Բաժին",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="description",
            field=models.TextField(verbose_name="Խնդրի Պահանջը"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="starter_code",
            field=models.TextField(verbose_name="Սկզբնական կոդ"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="test_cases",
            field=models.JSONField(verbose_name="Թեստեր (JSON)"),
        ),
    ]
