# Generated by Django 6.0.2 on 2026-05-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0007_solvedproblem"),
    ]

    operations = [
        migrations.AddField(
            model_name="solvedproblem",
            name="solution_code",
            field=models.TextField(blank=True, null=True, verbose_name="Լուծման կոդ"),
        ),
    ]
